image:
  repository: quay.io/gravitational/teleport
  tag: 4.0.2
  pullPolicy: IfNotPresent

strategy: RollingUpdate

service:
  type: NodePort
  ports:
    proxyweb:
      port: 3080
      targetPort: 3080
      nodePort: 30080
      protocol: TCP
    authssh:
      port: 3025
      targetPort: 3025
      nodePort: 30025
      protocol: TCP
    proxykube:
      port: 3026
      targetPort: 3026
      nodePort: 30026
      protocol: TCP
    proxyssh:
      port: 3023
      targetPort: 3023
      nodePort: 30023
      protocol: TCP
    proxytunnel:
      port: 3024
      targetPort: 3024
      nodePort: 30024
      protocol: TCP

ingress:
  enabled: false

ports:
  proxyweb:
    containerPort: 3080
  authssh:
    containerPort: 3025
  proxykube:
    containerPort: 3026
  proxyssh:
    containerPort: 3023
  nodessh:
    containerPort: 3022
  proxytunnel:
    containerPort: 3024

proxy:
  tls:
    enabled: true
    secretName: tls-web

license:
  enabled: false

config:
  teleport:
    log:
      output: stderr
      severity: DEBUG
    data_dir: /var/lib/teleport
    storage:
      type: dir

  auth_service:
    enabled: yes
    authentication:
      type: github
    public_addr: teleport.example.com:3025
    cluster_name: teleport.example.com

  ssh_service:
    enabled: yes
    public_addr: teleport.example.com:3022

  proxy_service:
    enabled: yes
    public_addr: teleport.example.com
    web_listen_addr: 0.0.0.0:3080
    listen_addr: 0.0.0.0:3023
    https_key_file: /var/lib/certs/tls.key
    https_cert_file: /var/lib/certs/tls.crt
    kubernetes:
      enabled: yes
      listen_addr: 0.0.0.0:3026

rbac:
  create: true

serviceAccount:
  create: true

persistence:
  enabled: false

automountServiceAccountToken: true
